// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqlyCwLdZmy_9hRzyX17jWQsBtPBuMDUs',
    appId: '1:857401068227:web:15736322a08b941a0fb076',
    messagingSenderId: '857401068227',
    projectId: 'glam-5677b',
    authDomain: 'glam-5677b.firebaseapp.com',
    storageBucket: 'glam-5677b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbrt-iOoFUYAeK8Lwzy6Azg0llAAMDEzg',
    appId: '1:857401068227:android:75cf926fcf734cc30fb076',
    messagingSenderId: '857401068227',
    projectId: 'glam-5677b',
    storageBucket: 'glam-5677b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpcuGWIl8rG0s_SoILVU1RggMWnY62QRk',
    appId: '1:857401068227:ios:0c515da1fba517250fb076',
    messagingSenderId: '857401068227',
    projectId: 'glam-5677b',
    storageBucket: 'glam-5677b.firebasestorage.app',
    iosBundleId: 'com.example.glam1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpcuGWIl8rG0s_SoILVU1RggMWnY62QRk',
    appId: '1:857401068227:ios:0c515da1fba517250fb076',
    messagingSenderId: '857401068227',
    projectId: 'glam-5677b',
    storageBucket: 'glam-5677b.firebasestorage.app',
    iosBundleId: 'com.example.glam1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqlyCwLdZmy_9hRzyX17jWQsBtPBuMDUs',
    appId: '1:857401068227:web:57fb87bde46eba940fb076',
    messagingSenderId: '857401068227',
    projectId: 'glam-5677b',
    authDomain: 'glam-5677b.firebaseapp.com',
    storageBucket: 'glam-5677b.firebasestorage.app',
  );
}
